name: My First GitHub Actions Success Test

on: [push]

jobs:
  build:
    # Tumhaare EC2 instance ko catch karne ke liye
    runs-on: self-hosted

    steps:
    # Code ko runner par pull karne ke liye
    - uses: actions/checkout@v3
    
    - name: Welcome Message
      run: |
        echo "=================================================="
        echo "Bhai, Aditya ka runner ekdum mast chal raha hai! 🎉"
        echo "=================================================="

    - name: Server Ki Details Check Karo
      run: |
        echo "Uptime dekhye server ka:"
        uptime
        echo "Kaun sa OS chal raha hai:"
        uname -a
        echo "Current User kaun hai:"
        whoami
